apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    uid: elasticsearch
    isDefault: false
    editable: false
    jsonData:
      index: "logs-otel*"
      timeField: "@timestamp"
      esVersion: "8.0.0"
      logMessageField: Body
      logLevelField: SeverityText

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-query:16686
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: elasticsearch
        tags:
          - key: service.name
            value: resource.service.name
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        query: "TraceId:\"$${__trace.traceId}\""
